CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_type ENUM('question','ai_answer','human_answer','login_success','login_failure','document_upload') NOT NULL,
  actor ENUM('resident','ai','human','admin','system') NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  message_id BIGINT UNSIGNED NULL,
  question MEDIUMTEXT NULL,
  answer MEDIUMTEXT NULL,
  ai_draft MEDIUMTEXT NULL,
  ai_confidence DECIMAL(5,4) NULL,
  ai_model VARCHAR(120) NULL,
  citations JSON NULL,
  source_ip VARCHAR(45) NULL,
  source_port SMALLINT UNSIGNED NULL,
  user_agent VARCHAR(512) NULL,
  request_method VARCHAR(16) NULL,
  request_uri VARCHAR(2048) NULL,
  referer VARCHAR(2048) NULL,
  forwarded_for VARCHAR(512) NULL,
  host VARCHAR(255) NULL,
  session_hash CHAR(64) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_audit_created_at (created_at),
  KEY idx_audit_conversation (conversation_id),
  KEY idx_audit_event (event_type),
  CONSTRAINT fk_audit_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_audit_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
